import React, { useState, useEffect, useRef } from "react";
import AnimateNumber from "@/components/animated-blur-number";
import { ShieldWarning as ShieldAlert, ArrowSquareOut as ExternalLink } from "@phosphor-icons/react";
import { Reveal } from "@/components/site/primitives";

const GlobalLeakCounter = () => {
  // Base fallback number (approx 17.6B)
  const [leakCount, setLeakCount] = useState(17667901961);
  const [isActive, setIsActive] = useState(false);
  const cardRef = useRef(null);

  useEffect(() => {
    // Fetch the latest real-world stats generated by the GitHub Action
    fetch("/data/leak-stats.json")
      .then((res) => res.json())
      .then((data) => {
        if (data && data.totalPwnCount) {
          setLeakCount(data.totalPwnCount);
        }
      })
      .catch(() => {});
  }, []);

  useEffect(() => {
    const card = cardRef.current;
    if (!card || !("IntersectionObserver" in window)) {
      setIsActive(true);
      return undefined;
    }

    const observer = new IntersectionObserver(
      ([entry]) => setIsActive(Boolean(entry?.isIntersecting) && !document.hidden),
      { rootMargin: "160px 0px" },
    );
    observer.observe(card);

    const onVisibility = () => {
      if (document.hidden) {
        setIsActive(false);
        return;
      }
      const rect = card.getBoundingClientRect();
      setIsActive(rect.bottom >= -160 && rect.top <= window.innerHeight + 160);
    };
    document.addEventListener("visibilitychange", onVisibility);

    return () => {
      observer.disconnect();
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, []);

  useEffect(() => {
    if (!isActive) return undefined;
    const intervalId = setInterval(() => {
      setLeakCount((prev) => prev + Math.floor(Math.random() * 8) + 1);
    }, 2000);
    return () => clearInterval(intervalId);
  }, [isActive]);

  return (
    <Reveal>
      <article ref={cardRef} aria-labelledby="leak-counter-title" className="relative overflow-hidden rounded-[32px] border border-white/5 bg-zinc-950 p-8 md:p-12 shadow-[0_0_80px_rgba(220,38,38,0.03)]">
        {/* Subtle red/amber radial gradient to warn about the danger */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_bottom_left,_var(--tw-gradient-stops))] from-red-950/20 via-zinc-950 to-zinc-950 pointer-events-none" />
        
        <div className="relative z-10 flex flex-col md:flex-row md:items-center md:justify-between gap-8">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-4">
              <ShieldAlert className="w-5 h-5 text-red-500/80" />
              <span className="font-mono text-[11px] uppercase tracking-widest text-red-500/80">
                Ameaça Global em Tempo Real
              </span>
            </div>
            
            <h2 id="leak-counter-title" className="mt-2 font-mono text-4xl md:text-6xl lg:text-7xl font-bold tracking-tighter text-white">
              <AnimateNumber 
                value={leakCount} 
                locale="pt-BR"
                blur={10}
                duration={600}
              />
            </h2>
            
            <p className="mt-4 max-w-xl text-base text-zinc-400 leading-relaxed">
              Contas e registros expostos globalmente. Cada vez que uma IA em nuvem processa seus dados, você está a um vazamento de entrar para essa estatística.
            </p>
            
            <div className="mt-6">
              <a 
                href="https://cybernews.com/personal-data-leak-check/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="group flex items-center gap-1.5 w-fit font-mono text-[10px] uppercase tracking-widest text-zinc-500 hover:text-zinc-300 transition-colors"
              >
                Base de dados: Cybernews Leak Check
                <ExternalLink className="w-3 h-3 opacity-50 group-hover:opacity-100 transition-opacity" />
              </a>
            </div>
          </div>
          
          <div className="hidden md:flex shrink-0">
            <div className="flex flex-col items-end gap-2 text-right">
              <span className="font-mono text-[10px] uppercase tracking-widest text-red-500/50">
                Status da Nuvem
              </span>
              <div className="flex items-center gap-2 bg-white/[0.03] rounded-full px-4 py-2">
                <span className="relative flex h-2 w-2">
                  <span className="absolute inline-flex h-full w-full rounded-full bg-red-500 opacity-75 animate-ping" />
                  <span className="relative inline-flex h-2 w-2 rounded-full bg-red-500" />
                </span>
                <span className="font-mono text-[11px] uppercase tracking-wider text-red-400">
                  Vazando Agora
                </span>
              </div>
            </div>
          </div>
        </div>
      </article>
    </Reveal>
  );
};

export default GlobalLeakCounter;
